agency/urls.py
from django.urls import path
from . import views
from .views import RoomDetailView, CancelBookingView, AddReview


urlpatterns = [
    path('', views.hotel_list, name='hotel_list'),
    path('hotel/<int:pk>/', views.hotel_detail, name='hotel_detail'),
    path('room_list/', views.RoomListView, name='room_list'),
    path('room/<category>', RoomDetailView.as_view(), name='room_detail'),
    path('booking_list/', views.booking_list, name='booking_list'),
    path('booking/cancel/<pk>', CancelBookingView.as_view(), name='room_cancel'),
    path('search_hotels/', views.search_hotels, name='search_hotels'),
    path('user/', views.user_page, name='user_page'),
    path('hotel/<int:pk>/add_review/', AddReview.as_view(), name='add_review')
]

travelagency/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('agency.urls')),
    path('logins/', include('django.contrib.auth.urls')),
    path('logins/', include('logins.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agency/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Hotel(models.Model):
    Cities = (
        ('Minsk', 'Minsk'),
        ('Brest', 'Brest'),
        ('Vitebsk', 'Vitebsk'),
        ('Mogilev', 'Mogilev'),
        ('Gomel', 'Gomel'),
        ('Grodno', 'Grodno'),
    )
    name = models.CharField(max_length=255)
    description = models.TextField()
    stars = models.IntegerField()
    location = models.CharField(max_length=10, choices=Cities)
    price = models.IntegerField(default=10)
    room_count = models.IntegerField(default=5)
    images = models.ImageField(upload_to="hotels/")

    def __str__(self):
        return f'{self.name}'


class Review(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name='reviews')
    name = models.CharField(max_length=255)
    body = models.TextField()
    date_add = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, related_name="author", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.hotel} - {self.name}'


class Room(models.Model):
    Room_Categories = (
        ('YAC', 'AC'),
        ('NAC', 'NON-AC'),
        ('DEL', 'DELUXE'),
        ('KIN', 'KING'),
    )
    number = models.IntegerField()
    category = models.CharField(max_length=3, choices=Room_Categories)
    beds = models.IntegerField()
    capacity = models.IntegerField()
    hotel = models.ForeignKey(Hotel, related_name='hotel_name', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.number}. {self.category} with {self.beds} beds for {self.capacity} people'


class HotelImage(models.Model):
    hotel = models.ForeignKey(Hotel, related_name="hotel_images", on_delete=models.CASCADE)
    images = models.ImageField(upload_to="images/")


class HotelBooking(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="user_booking", on_delete=models.CASCADE)
    check_in = models.DateField()
    check_out = models.DateField()

    def __str__(self):
        return f'{self.user} booking {self.room}'

    def cancel_booking(self):
        return reverse('room_cancel', args=[self.pk, ])

agency/forms.py
from django import forms
from .models import Hotel, HotelBooking, Review
from django.contrib.auth.models import User


class HotelForm(forms.ModelForm):
    class Meta:
        model = Hotel
        fields = ('name', 'description', 'stars', 'location')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class BookingForm(forms.ModelForm):
    class Meta:
        model = HotelBooking
        fields = ('check_in', 'check_out')


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('name', 'body')


class AvailabilityForm(forms.Form):
    check_in = forms.DateField(required=True, input_formats=["%Y-%m-%d", ])
    check_out = forms.DateField(required=True, input_formats=["%Y-%m-%d", ])

agency/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Hotel, HotelBooking, Room, Review
from .forms import HotelForm, BookingForm, AvailabilityForm, UserForm, ReviewForm
from django.views.generic import ListView, FormView, View, DeleteView, CreateView
from agency.booking.availability import check_availability
from django.urls import reverse, reverse_lazy
from django.core.paginator import Paginator
from .filters import HotelFilter


def user_page(request):
    user_form = UserForm(instance=request.user)
    return render(request=request, template_name='agency/profile_page.html',
                  context={'user': request.user, 'user_form': user_form})


def search_hotels(request):
    if request.method == "POST":
        search = request.POST['search']
        hotels = Hotel.objects.filter(name__contains=search)
        return render(request, 'agency/search_form.html', {'search': search, 'hotels': hotels})
    else:
        return render(request, 'agency/search_form.html', {})


def hotel_list(request):
    hotels = Hotel.objects.all()
    hotel_filter = HotelFilter(request.GET, queryset=hotels)
    pag = Paginator(Hotel.objects.all(), 2)
    page = request.GET.get('page')
    hotel = pag.get_page(page)
    return render(request, 'agency/hotel_list.html', {
        'hotels': hotels,
        'hotel': hotel,
        'hotel_filter': hotel_filter
    })


def hotel_detail(request, pk):
    hotel = get_object_or_404(Hotel, pk=pk)
    return render(request, 'agency/hotel_detail.html', {'hotel': hotel})


def booking_list(request):
    if request.user.is_staff:
        bookings = HotelBooking.objects.all()
        return render(request, 'agency/booking_list.html', {'bookings': bookings})
    else:
        bookings = HotelBooking.objects.filter(user=request.user)
        return render(request, 'agency/booking_list.html', {'bookings': bookings})


def RoomListView(request):
    room = Room.objects.all()[0]
    rooms = Room.objects.all()
    room_categories = dict(room.Room_Categories)
    room_values = room_categories.values()
    room_list = []
    for room_category in room_categories:
        room = room_categories.get(room_category)
        room_url = reverse('room_detail', kwargs={'category': room_category})
        room_list.append((room, room_url))
    context = {
        'room_list': room_list,
        'rooms': rooms
    }
    return render(request, 'agency/room_list.html', context)


class RoomDetailView(View):
    def get(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        form = AvailabilityForm()
        room_list = Room.objects.filter(category=category)
        if len(room_list):
            room = room_list[0]
            room_category = dict(room.Room_Categories).get(room.category, None)
            context = {
                'room_category': room_category,
                'form': form,
            }
            return render(request, 'agency/room_detail.html', context)
        else:
            return HttpResponse('Category does not exist')

    def post(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        room_list = Room.objects.filter(category=category)
        form = AvailabilityForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
        available_rooms = []
        for room in room_list:
            if check_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)

        if len(available_rooms) > 0:
            room = available_rooms[0]
            booking = HotelBooking.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out'],
            )
            booking.save()
            return HttpResponse(booking)
        else:
            return HttpResponse('All of this category of rooms are booked!')


class CancelBookingView(DeleteView):
    model = HotelBooking
    template_name = 'agency/booking_cancel.html'
    success_url = reverse_lazy('booking_list')


class AddReview(CreateView):
    model = Review
    form_class = ReviewForm
    template_name = 'agency/review_form.html'

    def form_valid(self, form):
        form.instance.hotel_id = self.kwargs['pk']
        return super().form_valid(form)

    success_url = reverse_lazy('hotel_list')

agency/templates/agency/availability_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book a Room</title>
</head>
<body>
    <form action ="" method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <button type="submit">Book Room</button>
    </form>
</body>
</html>

agency/templates/agency/base.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/test.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:wght@700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a183da9427.js" crossorigin="anonymous"></script>
  <title>Loading</title>
</head>
<body>

{% include 'agency/navbar.html' %}
        {% if messages %}
            {% for message in messages %}
               <div class="alert alert-warning" role="alert">
                {{ message }}
                </div>


            {% endfor %}
        {% endif %}
            {% block content %}
            {% endblock %}
</body>
</html>

agency/templates/agency/booking_cancel.html
{% extends 'agency/base.html' %}

{% block content %}
<!-- jumbotron and nav -->
  <nav class="navbar navbar-expand-lg justify-content-between navbar-dark" role="navigation">
    <div class="navbar-brand">
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
  </nav>
  <div class="container">
    <div class="row mt-2 ">
      <div class="col-md-7 mt-text text-white align-self-center mb-2">
        <h1>Eclipse</h1>
      </div>
      <div class="col-md-5 col-md-push-1">
        <div class=" form-card">
          <h3>Are you sure?</h3>
          <form id="booking-form" action="" method="POST">
            {% csrf_token %}
            <div class="row form-group">
              <div class="col-md-12">
                <input type="submit" class="btn btn-danger btn-block" value="Cancel the Booking">
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- suggestions -->
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 text-center my-5">
        <h2>{{room_category}}</h2>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-sm-12">
        <!-- tabs for sections suggestions -->
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="top-cities-tab" data-toggle="tab" href="#top-cities" role="tab" aria-controls="top-cities" aria-selected="true">Top Cities</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="top-destinations-tab" data-toggle="tab" href="#top-destinations" role="tab" aria-controls="top-destinations" aria-selected="false">Top Countries</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="best-offers-tab" data-toggle="tab" href="#best-offers" role="tab" aria-controls="best-offers" aria-selected="false">Best Offers</a>
          </li>
        </ul>
        <div class="tab-content" id="myTabContent">
          <!-- Top Cities -->
          <div class="tab-pane fade show active" id="top-cities" role="tabpanel" aria-labelledby="top-cities-tab">
            <section class="row">
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="http://placeimg.com/640/640/arch" alt="Card image cap">
                  <div class="card-body">
                    <div class="">
                      <h5>
                        <a href="">New York, USA</a>
                      </h5>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia..</p>
                      <p>
                        <a href="pricing.html">
														<span class="btn btn-primary">View Offers</span>
													</a>
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="http://placeimg.com/640/640/arch" alt="Card image cap">
                  <div class="card-body ">
                    <div class="">
                      <h5>Seoul, South Korea</h5>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia..</p>
                      <p>
                        <a href="pricing.html">
														<span class="btn btn-primary">View Offers</span>
													</a>
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="http://placeimg.com/640/640/arch" alt="Card image cap">
                  <div class="card-body">
                    <div class="">
                      <h5>Paris, France</h5>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia..</p>
                      <p>
                        <a href="pricing.html">
														<span class="btn btn-primary">View Offers</span>
													</a>
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="http://placeimg.com/640/640/arch" alt="Card image cap">
                  <div class="card-body">
                    <div class="">
                      <h5>Paris, France</h5>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia..</p>
                      <p>
                        <a href="pricing.html">
														<span class="btn btn-primary">View Offers</span>
													</a>
                      </p>
                    </div>
                  </div>
                </div>
              </article>
            </section>
          </div>

          <!-- Top Countries -->
          <div class="tab-pane fade" id="top-destinations" role="tabpanel" aria-labelledby="top-destinations-tab">
            <section class="row">
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="http://placeimg.com/640/640/arch" alt="Card image cap">
                  <div class="card-body">
                    <div class="">
                      <h5>
                        <a href="">New York, USA</a>
                      </h5>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia..</p>
                      <p>
                        <a href="country.html">
														<span class="btn btn-primary">Suggest Places</span>
													</a>
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="http://placeimg.com/640/640/arch" alt="Card image cap">
                  <div class="card-body ">
                    <div class="">
                      <h5>Seoul, South Korea</h5>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia..</p>
                      <p>
                        <a href="country.html">
														<span class="btn btn-primary">Suggest Places</span>
													</a>

                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="http://placeimg.com/640/640/arch" alt="Card image cap">
                  <div class="card-body">
                    <div class="">
                      <h5>Paris, France</h5>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia..</p>
                      <p>
                        <a href="country.html">
														<span class="btn btn-primary">Suggest Places</span>
													</a>
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="http://placeimg.com/640/640/arch" alt="Card image cap">
                  <div class="card-body">
                    <div class="">
                      <h5>Paris, France</h5>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia..</p>
                      <p>
                        <a href="country.html">
														<span class="btn btn-primary">Suggest Places</span>
													</a>
                      </p>
                    </div>
                  </div>
                </div>
              </article>
            </section>
          </div>
          <!-- Highly Rated -->
          <div class="tab-pane fade" id="best-offers" role="tabpanel" aria-labelledby="best-offers-tab">
            <section class="row">
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="http://placeimg.com/640/640/arch" alt="Card image cap">
                  <div class="card-body">
                    <div class="">
                      <h5>
                        <a href="">New York, USA</a>
                      </h5>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia..</p>
                      <p>
                        <a href="pricing.html">
														<span class="btn btn-primary">View Offers</span>
													</a>
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="http://placeimg.com/640/640/arch" alt="Card image cap">
                  <div class="card-body ">
                    <div class="">
                      <h5>Seoul, South Korea</h5>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia..</p>
                      <p>
                        <a href="pricing.html">
														<span class="btn btn-primary">View Offers</span>
													</a>
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="http://placeimg.com/640/640/arch" alt="Card image cap">
                  <div class="card-body">
                    <div class="">
                      <h5>Paris, France</h5>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia..</p>
                      <p>
                        <a href="pricing.html">
														<span class="btn btn-primary">View Offers</span>
													</a>
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="http://placeimg.com/640/640/arch" alt="Card image cap">
                  <div class="card-body">
                    <div class="">
                      <h5>Paris, France</h5>
                      <p>Far far away, behind the word mountains, far from the countries Vokalia..</p>
                      <p>
                        <a href="pricing.html">
														<span class="btn btn-primary">View Offers</span>
													</a>
                      </p>
                    </div>
                  </div>
                </div>
              </article>
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




{% endblock %}

agency/templates/agency/booking_list.html
{% extends 'agency/base.html' %}

{% block content %}
<!-- jumbotron and nav -->
  <nav class="navbar navbar-expand-lg justify-content-between navbar-dark" role="navigation">
    <div class="navbar-brand">
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
  </nav>
  <div class="container">
    <div class="row mt-2 ">
      <div class="col-md-7 mt-text text-white align-self-center mb-2">
        <h1>Eclipse</h1>
      </div>
    </div>
  </div>
</section>

<!-- suggestions -->
<div class="section">
  <div class="container">
    <div class="row mb-3">
      <div class="col-sm-12">
        <!-- tabs for sections suggestions -->
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="top-cities-tab" data-toggle="tab" href="#top-cities" role="tab" aria-controls="top-cities" aria-selected="true">Bookings</a>
          </li>
        </ul>
        <div class="tab-content" id="myTabContent">
          <!-- Top Cities -->
          <div class="tab-pane fade show active" id="top-cities" role="tabpanel" aria-labelledby="top-cities-tab">
            <section class="row">
              {% for booking in bookings %}
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="https://www.italianbark.com/wp-content/uploads/2018/01/hotel-room-design-trends-italianbark-interior-design-blog.jpg" alt="Card image cap">
                  <div class="card-body">
                    <div class="">
                      <center>
                      <h4>
                        <a>{{booking.room.category}} Suite</a>
                      </h4>
                        </center>
                      <h5>
                        <a>From: {{booking.check_in}}</a>
                      </h5>
                      <h5>
                        <a>To: {{booking.check_out}}</a>
                      </h5>
                      <h5>
                        <a>Beds: {{booking.room.beds}}</a>
                      </h5>
                      <h5>
                        <a>Capacity: {{booking.room.capacity}}</a>
                      </h5>
                        <a href="{{booking.cancel_booking}}">
                          <span class="btn btn-secondary">Cancel</span>
                        </a>
                      </p>
                    </div>
                  </div>
                </div>
              </article>
              {% endfor %}
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




{% endblock %}

agency/templates/agency/hotel_detail.html
{% extends 'agency/base.html' %}

{% block content %}
<!-- jumbotron and nav -->
  <nav class="navbar navbar-expand-lg justify-content-between navbar-dark" role="navigation">
    <div class="navbar-brand">
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
  </nav>
  <div class="container">
    <div class="row mt-2 ">
      <div class="col-md-7 mt-text text-white align-self-center mb-2">
        <h1>Eclipse</h1>
      </div>
      <div class="col-md-5 col-md-push-1">
        <div class=" form-card">
          <h3>{{hotel.name}}</h3>
          <form action="#">
            <div class="row form-group">
              <div class="col-md-12">
                <label for="destination">Location: {{ hotel.location }}</label>
                <i class="fas fa-location-arrow"></i>
              </div>
            </div>
            <div class="row form-group">
              <div class="col-md-12">
                <label for="destination">Stars: {{ hotel.stars }}</label>
                <i class="fas fa-award"></i>
              </div>
            </div>
            <div class="row form-group">
              <div class="col-md-12">
                <label for="destination">Types of Rooms: 5</label>
                <i class="fas fa-bed"></i>
              </div>
            </div>
            <div class="row form-group">
              <div class="col-md-12">
                <label for="destination">Reviews: 4</label>
                <i class="	fas fa-comment"></i>
              </div>
            </div>
            <div class="row form-group">
              <div class="col-md-12">
                <label for="destination">Price: {{hotel.price}}</label>
                <i class="	fas fa-dollar-sign"></i>
              </div>
            </div>
            <div class="row form-group">
              <div class="col-md-12">
                <label for="destination">Room Count: {{hotel.room_count}}</label>
                <i class="	fas fa-couch"></i>
              </div>
            </div>

            {% if user.is_authenticated %}
            <div class="row form-group">
              <div class="col-md-12">
                <a class="btn btn-primary btn-block" href="{% url 'room_list' %}">Choose Room</a>
              </div>
            </div>
            {% endif %}
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- suggestions -->
<div class="section">
  <div class="container">
    <div class="row">
    </div>
    <div class="row mb-3">
      <div class="col-sm-12">
        <!-- tabs for sections suggestions -->
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="top-cities-tab" data-toggle="tab" href="" role="tab" aria-controls="top-cities" aria-selected="true">Gallery</a>
          </li>
        </ul>
        <div class="tab-content" id="myTabContent">
          <!-- Top Cities -->
          <div class="tab-pane fade show active" id="top-cities" role="tabpanel" aria-labelledby="top-cities-tab">
            <section class="row">
              {% for image in hotel.hotel_images.all %}
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <img class="card-img-top" src="{{image.images.url}}" alt="Card image cap">
                </div>
              </article>
              {% endfor %}
            </section>
          </div>
          <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
            <a class="nav-link active" id="top-cities-tab" data-toggle="tab" href="" role="tab" aria-controls="top-cities" aria-selected="true">Reviews</a>
            </li>
          </ul>
          <section class="row">
            {% for review in hotel.reviews.all %}
              <article class="col-lg-3 col-md-4 col-sm-6 p-2">
                <div class="card hotel-card">
                  <h4>{{ review.name }}</h4>
                  <hr>
                  {{ review.body }}
                  </br></br>
                  {{review.date_add}} - {{review.user}}
                </div>
              </article>
              {% endfor %}
            </section>
          {% if user.is_authenticated %}
          <div class="card-body">
              <div class="">
                <a href="{% url 'add_review' hotel.pk %}">
                  <span class="btn btn-primary">Add Review</span>
                </a>
              </div>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

agency/templates/agency/room_detail.html
{% extends 'agency/base.html' %}

{% block content %}
<!-- jumbotron and nav -->
  <nav class="navbar navbar-expand-lg justify-content-between navbar-dark" role="navigation">
    <div class="navbar-brand">
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
  </nav>
  <div class="container">
    <div class="row mt-2 ">
      <div class="col-md-7 mt-text text-white align-self-center mb-2">
        <h1>Eclipse</h1>
      </div>
      <div class="col-md-5 col-md-push-1">
        <div class=" form-card">
          </br>
          <h5>{{room_category}} Room</h5>
          <form id="booking-form" action="" method="POST">
            {% csrf_token %}
            <div class="row form-group">
              <div class="col-md-6">
                <label for="id_check_in">Check in</label>
                <p>
                  <input type="date" name="check_in" id="id_check_in" class="form-control">
                </p>
              </div>
              <div class="col-md-6">
                <label for="id_check_out">Check out</label>
                <p>
                  <input type="date" name="check_out" id="id_check_out" class="form-control">
                </p>
              </div>
            </div>
            <div class="row form-group">
              <div class="col-md-12">
                <input type="submit" class="btn btn-primary btn-block" value="Book the Room">
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>





{% endblock %}